name: First workflow
on:
  pull_request:
    types: [opened]
      
jobs:
  build:
    name: Runner and branch info
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: runer info
        run: |
          echo "Runner used is: ${{ RUNNER_OS }}"
